name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9
  - psutil
  - toolz
  - dill
  - partd
  - bokeh
  - dask
  - pip
  - pip:
    - plotly 
    - scikit-learn
    - matplotlib
    - pandas
    - numpy

